### ISSUE TITLE
Question: Morevna edition will be release?

### ISSUE THREAD

**Issue by Lvaskz** [flathub/io.github.OpenToonz#1]
Hi, I know there is exists a versión about opentoonz morevna edtion1.2.0.2, vey cool. Will be release in the near future?

**Comment by eszlari** [comment]
Link?

**Comment by Lvaskz** [comment]
https://morevnaproject.org/opentoonz/ here and 
https://github.com/morevnaproject/opentoonz/tree/morevna here

**Comment by eszlari** [comment]
It seems like all the modification should make it upstream at some point:

https://github.com/morevnaproject/opentoonz/issues/11#issuecomment-399767138

> No, we are not fork. The features developed by our team are submitted to official OpenToonz version and (eventually) getting merged.
> 
> We also providing early testing builds with our changes to allow people do early testing of new features.
