### ISSUE TITLE
cannot access ffmpeg

### ISSUE THREAD

**Issue by nootc** [flathub/io.github.OpenToonz#15]
Manjaro KDE 64 bit
I have put /usr/bin as the path for ffmpeg but I do not get mp4, webm, or gif as options to render my file. I tried the OpenToonz package from Manjaro's official repository and ffmpeg works fine, but I would prefer to use the flatpak.
![opentoonz_ffmpeg_path](https://user-images.githubusercontent.com/78979619/164554093-a60a9ac8-770c-4b24-845b-e36aea21f6ef.png)
![opentoonz_output_settings](https://user-images.githubusercontent.com/78979619/164554155-bc6b5ad4-1a26-4986-aeb1-d285e5f89fa3.png)

**Comment by hfiguiere** [comment]
you can't access the ffmpeg on you "host" (Distro).

**Comment by nootc** [comment]
What is the intended way to access ffmpeg?

**Comment by hfiguiere** [comment]
it is build in the Flatpak, so I'm not sure what problems you are having. It's in `/app/bin`

**Comment by nootc** [comment]
Okay. It works now. Thanks for helping.
