### ISSUE TITLE
Doesn't run under Xorg or Wayland

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/io.github.OpenToonz#2]
This is on Fedora 28 KDE with Wayland:

```
flatpak run io.github.OpenToonz
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
plugin search directory:/home/awilms/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/awilms/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
QWaylandGLContext: failed to create EGLContext, error=3009
ASSERT: "QOpenGLContext::currentContext()" in file qgl.cpp, line 88
```

```
flatpak run --nosocket=wayland io.github.OpenToonz
Failed to create display (No such file or directory)
```

Not sure if this is packaging related or if it should also be reported upstream.

Edit: Found this related Qt bug: https://bugreports.qt.io/browse/QTBUG-63524

**Comment by nedrichards** [comment]
Hrm, yeah, that seems awkward. It works fine for me on a pure X11 system.

**Comment by Alexander-Wilms** [comment]
Yes, that does work.

**Comment by eszlari** [comment]
I think this should work under Plasma 5.13, afaik they changed setup logic for Qt's backend there.

**Comment by eszlari** [comment]
@Alexander-Wilms Can you test this again with Plasma 5.13 (now available in Fedora 28)? It should work there without QT_QPA_PLATFORM, see: https://github.com/flathub/org.kde.kdenlive/issues/18

**Comment by Alexander-Wilms** [comment]
Can confirm that it works fine now.
