### ISSUE TITLE
No MP4 File After Render

### ISSUE THREAD

**Issue by nootc** [flathub/io.github.OpenToonz#25]
When I try to render to an mp4, the program goes through the process of rendering, but once it is completed, there is no mp4 file in the expected location. There is no error message.

**Comment by nootc** [comment]
I found a work around. I changed the ffmpeg directory to /app/bin, but instead of restarting the application, I just continue working. The render will then just work. Every time I restart the application, the ffmpeg directory is changed back to /usr/bin, which does not work.

**Comment by sfetzel** [comment]
> I found a work around. I changed the ffmpeg directory to /app/bin, but instead of restarting the application, I just continue working. The render will then just work. Every time I restart the application, the ffmpeg directory is changed back to /usr/bin, which does not work.

I can confirm this behaviour. Changing the ffmpeg path in the settings will be written to the preferences.ini. When closing and starting OpenToonz again, the ffmpeg path is reset to /usr/bin.
