### ISSUE TITLE
Fail to install dependency VAAPI Intel

### ISSUE THREAD

**Issue by chengjk84** [flathub/io.github.OpenToonz#4]
## Linux distribution and version
Fedora 28

## Flatpak version
Flatpak 0.99.2

## Description of the problem
Installing in system:
io.github.OpenToonz/x86_64/stable        flathub fe18e6d57ac6
  permissions: ipc, wayland, x11, dri
  file access: host
io.github.OpenToonz.Locale/x86_64/stable flathub bd9c6985d1c0
Updating in system:
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 gnome 82006efc71d3
org.freedesktop.Platform.ffmpeg/x86_64/1.6      gnome d757f762489e
Updating: org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 from gnome
error: Failed to update org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6: Server returned HTTP 404

## Steps to reproduce
flatpak install flathub io.github.OpenToonz -y

**Comment by nedrichards** [comment]
Oh! That's not great. That doesn't sound like an opentoonz issue though...

**Comment by chengjk84** [comment]
I know, i did try to manually upgrade VAAPI.Intel package, but it didn't show any update required... by the way VAAPI already installed from installing other application...

**Comment by nedrichards** [comment]
oh, iiinteresting. I'll check what version's there.

**Comment by eszlari** [comment]
Since this is not specific to opentoonz, I'm closing this issue.

https://github.com/flatpak/flatpak/issues/1907
