### ISSUE TITLE
Update from 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.OpenToonz#5]
I see the manifest uses the KDE 5.10 SDK which is based upon Qt 5.10. This is now out of security support and won't recieve further updates. It'd be good to move to either the 5.9 lts or the newer and fresher 5.11 SDK.

**Comment by eszlari** [comment]
I will have to switch to 5.9, because this crash bug with 5.11 has not been fixed yet:
https://github.com/opentoonz/opentoonz/issues/2107

**Comment by eszlari** [comment]
Switched to 5.9: https://github.com/flathub/io.github.OpenToonz/commit/4e728863e36ac93fed8b9edbbee7976556787afa
